language: c

compiler:
  - gcc
  - clang

#env:
#  matrix:
#  - GCC_VERSION=6
#  - GCC_VERSION=4

#matrix:
#
#  include:
#  - env: GCC_VERSION=6

install:
  - sudo add-apt-repository ppa:dns/gnu -y
  - sudo apt-get -qq update
  - sudo apt-get -qq install libpopt-dev libselinux1-dev libacl1-dev automake dash g++-6

script:
  - ./autogen.sh
  - ./configure
  - make
  - make test
  - cd test && LOGROTATE=../logrotate /bin/dash test && cd ..
  - make distcheck

notifications:
  email:
    recipients:
      - logrotate-owner@fedoraproject.org
    on_success: always
    on_failure: always

# vim:et:ts=2:sw=2
