sudo: required
language: c

services:
    - docker

script:
  - docker-compose run ubuntu:precise

notifications:
  email:
    recipients:
      - logrotate-owner@fedoraproject.org
    on_success: always
    on_failure: always

# vim:et:ts=2:sw=2
