sudo: required
language: c

services:
    - docker

matrix:
  include:
    - env: PLATFORM=ubuntu/precise
    - env: PLATFORM=ubuntu/trusty

script: |
  type docker
  type docker-compose
  make -C ci $PLATFORM

# vim:et:ts=2:sw=2
