language: c

compiler:
  - gcc
  - clang

env:
  matrix:
    - COMPILER=gcc
    - COMPILER=gcc-6
    - COMPILER=clang

matrix:
  exclude:
  # exclude impossible combinations
  - env: COMPILER=gcc-6
    compiler: clang
  - env: COMPILER=gcc
    compiler: clang
  - env: COMPILER=clang
    compiler: gcc

install:
  - sudo add-apt-repository ppa:dns/gnu -y
  - sudo apt-get -qq update
  - sudo apt-get -qq install libpopt-dev libselinux1-dev libacl1-dev automake dash g++-6

script:
  - ./autogen.sh
  - ./configure
  - make
  - make test
  - cd test && LOGROTATE=../logrotate /bin/dash test && cd ..
  - make distcheck

notifications:
  email:
    recipients:
      - logrotate-owner@fedoraproject.org
    on_success: always
    on_failure: always

# vim:et:ts=2:sw=2
