sudo: required
language: c

services:
  - docker

env:
  - PLATFORM=ubuntu/precise
# trusty tests fail: https://travis-ci.org/glensc/logrotate/builds/182442700
#  - PLATFORM=ubuntu/trusty
  - PLATFORM=ubuntu/xenial
  - PLATFORM=ubuntu/yakkety
  - PLATFORM=ubuntu/zesty
  - PLATFORM=fedora/21
  - PLATFORM=fedora/22
  - PLATFORM=fedora/23
  - PLATFORM=fedora/24
  - PLATFORM=fedora/25
  - PLATFORM=fedora/rawhide
  - PLATFORM=centos/centos7

script:
  - docker --version
  - docker-compose --version
  - make -C ci $PLATFORM

# vim:et:ts=2:sw=2
