sudo: required
language: c

services:
  - docker

matrix:
	include:
    - os: linux
      sudo: required
      env: PLATFORM=ubuntu/precise
    - os: linux
      sudo: required
      env: PLATFORM=ubuntu/trusty

script:
  - docker --version
  - docker-compose --version
  - make -C ci $PLATFORM

# vim:et:ts=2:sw=2
