sudo: required
language: c

services:
  - docker

matrix:
  include:
    - os: linux
      env: PLATFORM=ubuntu/precise
    - os: linux
      env: PLATFORM=ubuntu/trusty
    - os: linux
      env: PLATFORM=ubuntu/xenial
    - os: linux
      env: PLATFORM=ubuntu/yakkety
    - os: linux
      env: PLATFORM=ubuntu/zesty

script:
  - docker --version
  - docker-compose --version
  - make -C ci $PLATFORM

# vim:et:ts=2:sw=2
