sudo: required
dist: precise
language: c

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

install:
  - sudo add-apt-repository ppa:dns/gnu -y
  - sudo apt-get -qq update
  - sudo apt-get -qq install libpopt-dev libselinux1-dev libacl1-dev automake dash g++-6

script:
  - ./autogen.sh
  - ./configure CC=$COMPILER
  - make
  - make test
  - cd test && LOGROTATE=../logrotate /bin/dash test && cd ..
  - make distcheck

notifications:
  email:
    recipients:
      - logrotate-owner@fedoraproject.org
    on_success: always
    on_failure: always

# vim:et:ts=2:sw=2
