sudo: required
language: c

services:
  - docker

env:
  - PLATFORM=ubuntu/precise
# trusty tests fail: https://travis-ci.org/glensc/logrotate/builds/182442700
#  - PLATFORM=ubuntu/trusty
  - PLATFORM=ubuntu/xenial
  - PLATFORM=ubuntu/yakkety
  - PLATFORM=ubuntu/zesty

script:
  - docker --version
  - docker-compose --version
  - make -C ci $PLATFORM

# vim:et:ts=2:sw=2
