sudo: required
language: c

services:
  - docker

env:
  - PLATFORM=ubuntu/precise
  - PLATFORM=ubuntu/trusty
  - PLATFORM=ubuntu/xenial
  - PLATFORM=ubuntu/yakkety
  - PLATFORM=ubuntu/zesty

script:
  - docker --version
  - docker-compose --version
  - make -C ci $PLATFORM

# vim:et:ts=2:sw=2
